# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94688287ecbb176ae7c3971e8628965ccf93239a37f8f805b1030060a5ed3529abd598ec8bfa505084b972cbbd3e6e8f432d286f3afe9ba0ec47caa3246df2b9

test:
  secret_key_base: 720cccaf55d5fc94cb16ad12593163e4d794644fe44ef9ff91e0233dafc7605fd70f78b39d2c96e8966e944eee7d583a952077e89f88c49614db6f0c29369cbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
